FROM alpine:3.5

RUN apk update && \
  apk add \
    ca-certificates \
    git \
    openssh \
    curl \
    perl && \
  rm -rf /var/cache/apk/*

ADD drone-git /bin/

ENV HTTPS_PROXY http://10.200.20.61:8118

ENV HTTP_PROXY http://10.200.20.61:8118

ENTRYPOINT ["/bin/drone-git"]
